# Generated by Django 4.2.4 on 2023-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('ENG', 'Engineer'), ('MNG', 'Manager')], default='ENG', max_length=150, verbose_name='Employee Position'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'User with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
