# Generated by Django 4.2.4 on 2023-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_myuser_first_name_myuser_last_name_myuser_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Manager', 'Manager')], default='Engineer', max_length=150, verbose_name='Employee Position'),
        ),
    ]
