# Generated by Django 4.2.4 on 2023-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0006_myuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'User with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Manager', 'Manager')], default='Engineer', max_length=150, verbose_name='employee position'),
        ),
    ]
