# Generated by Django 4.2.4 on 2023-10-29 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0009_delete_engineerregisterationtoken'),
        ('engineer', '0002_delete_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerRegisterationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Engineer Token')),
                ('expired_date', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='manager.company')),
            ],
        ),
    ]
