# Generated by Django 4.2.4 on 2023-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0005_alter_engineerregisterationtoken_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerregisterationtoken',
            name='expired_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
