# Generated by Django 4.2.4 on 2023-09-27 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Division Name')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('project', models.CharField(help_text='Project Name', max_length=1000, verbose_name='Porject Name')),
                ('field', models.CharField(max_length=50, verbose_name='Division field')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='Responsible Person')),
                ('observation_type', models.CharField(choices=[('NGT', 'Negative'), ('POS', 'Positive')])),
                ('division', models.ManyToManyField(related_name='division_irs', to='irr_app.divisions', verbose_name='Division')),
                ('engineer', models.ManyToManyField(help_text='Engineer', limit_choices_to={'is_active': True, 'position': 'Engineer'}, related_name='my_irs', to=settings.AUTH_USER_MODEL, verbose_name='Engineer')),
                ('observations', models.ManyToManyField(related_name='ir', to='irr_app.observations')),
            ],
        ),
    ]
