# Generated by Django 4.2.4 on 2023-09-27 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Division Name'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='division',
            field=models.ManyToManyField(blank=True, null=True, related_name='division_irs', to='irr_app.divisions', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='engineer',
            field=models.ManyToManyField(blank=True, help_text='Engineer', limit_choices_to={'is_active': True, 'position': 'Engineer'}, null=True, related_name='my_irs', to=settings.AUTH_USER_MODEL, verbose_name='Engineer'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Division field'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='observation_type',
            field=models.CharField(blank=True, choices=[('NGT', 'Negative'), ('POS', 'Positive')], null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='observations',
            field=models.ManyToManyField(blank=True, null=True, related_name='ir', to='irr_app.observations'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='project',
            field=models.CharField(blank=True, help_text='Project Name', max_length=1000, null=True, verbose_name='Porject Name'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsible Person'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
