# Generated by Django 4.2.4 on 2023-09-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_enmployees_company_employees_and_more'),
        ('irr_app', '0002_alter_divisions_name_alter_inspectionreport_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irs', to='manager.company', verbose_name='Company Name'),
        ),
    ]
