# Generated by Django 4.2.4 on 2023-09-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0003_inspectionreport_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='division',
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_irs', to='irr_app.divisions', verbose_name='Division'),
        ),
    ]
