# Generated by Django 4.2.4 on 2023-09-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0004_remove_inspectionreport_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('inspection_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs', to='irr_app.inspectionreport')),
            ],
        ),
        migrations.RenameModel(
            old_name='Divisions',
            new_name='Division',
        ),
        migrations.DeleteModel(
            name='Observations',
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='observations',
            field=models.ManyToManyField(blank=True, null=True, related_name='ir', to='irr_app.observation'),
        ),
    ]
