# Generated by Django 4.2.4 on 2023-09-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0005_observation_rename_divisions_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='inspection_report',
        ),
    ]
