# Generated by Django 4.2.4 on 2023-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0006_remove_observation_inspection_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='date',
            field=models.DateField(),
        ),
    ]
