# Generated by Django 4.2.4 on 2023-10-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_enmployees_company_employees_and_more'),
        ('irr_app', '0007_alter_inspectionreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_dvs', to='manager.company', verbose_name='Division Company'),
        ),
    ]
