# Generated by Django 4.2.4 on 2023-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0010_remove_inspectionreport_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='ir_type',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive')], null=True),
        ),
    ]
