# Generated by Django 4.2.4 on 2023-10-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0011_alter_inspectionreport_ir_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='project',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Project Name'),
        ),
    ]
