# Generated by Django 4.2.4 on 2023-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0013_alter_inspectionreport_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
