# Generated by Django 4.2.4 on 2023-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0018_alter_inspectionreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='status',
            field=models.CharField(blank=True, default='Open', null=True),
        ),
    ]
