# Generated by Django 4.2.4 on 2023-11-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0020_alter_inspectionreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Close date'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='target_date',
            field=models.DateField(null=True, verbose_name='IR target date'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Overdue', 'Overdue')], default='Open', null=True, verbose_name='IR status'),
        ),
    ]
