# Generated by Django 4.2.4 on 2023-11-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0021_inspectionreport_close_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionreport',
            options={'ordering': ['id']},
        ),
    ]
