# Generated by Django 4.2.4 on 2023-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0022_alter_inspectionreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionreport',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='closed',
            field=models.BooleanField(default=False, null=True, verbose_name='IR closed'),
        ),
    ]
