# Generated by Django 4.2.4 on 2023-11-06 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irr_app', '0023_alter_inspectionreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_irs', to='irr_app.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='engineer',
            field=models.ManyToManyField(blank=True, help_text='Engineer', limit_choices_to={'is_active': True, 'position': 'Engineer'}, null=True, related_name='my_irs', to=settings.AUTH_USER_MODEL, verbose_name='Engineer'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Division field'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evidences'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='ir_type',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive')], null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='observations',
            field=models.ManyToManyField(blank=True, null=True, related_name='ir', to='irr_app.observation'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='project',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsible Person'),
        ),
    ]
