# Generated by Django 4.2.4 on 2023-11-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0024_alter_inspectionreport_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='closed',
        ),
    ]
