# Generated by Django 4.2.4 on 2023-11-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0025_remove_inspectionreport_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='closed',
            field=models.BooleanField(default=False, null=True, verbose_name='IR closed'),
        ),
    ]
