# Generated by Django 4.2.4 on 2023-11-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0026_inspectionreport_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='closed',
        ),
    ]
