# Generated by Django 4.2.4 on 2023-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irr_app', '0028_alter_inspectionreport_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='ir_type',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive')], null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('close', 'Close'), ('overdue', 'Overdue')], default=('open', 'Open'), null=True, verbose_name='IR status'),
        ),
    ]
