# Generated by Django 4.2.4 on 2023-09-18 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_alter_manager_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enmployees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'position': 'Engineer'}, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'position': 'Manager'}, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
