# Generated by Django 4.2.4 on 2023-09-18 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_company_enmployees_company_managers_delete_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='enmployees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'position': 'Engineer'}, related_name='employee_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'position': 'Manager'}, related_name='manager_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
