# Generated by Django 4.2.4 on 2023-09-20 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0005_alter_company_options_alter_company_enmployees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='enmployees',
            new_name='employees',
        ),
        migrations.AlterField(
            model_name='company',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'position': 'Manager'}, related_name='manager_company', to=settings.AUTH_USER_MODEL, verbose_name='QC Managers'),
        ),
    ]
