# Generated by Django 4.2.4 on 2023-10-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_enmployees_company_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerRegisterationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(null=True, verbose_name='Engineer Token')),
                ('expired_data', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='manager.company')),
            ],
        ),
    ]
