# Generated by Django 4.2.4 on 2023-10-28 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_engineerregisterationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerregisterationtoken',
            old_name='expired_data',
            new_name='expired_date',
        ),
        migrations.AlterField(
            model_name='engineerregisterationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid5, editable=False, null=True, verbose_name='Engineer Token'),
        ),
    ]
